/* Generated By:JavaCC: Do not edit this line. JCRParserConstants.java */
package net.jaardvark.jcr.txt2jcr.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JCRParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int STRING = 3;
  /** RegularExpression Id. */
  int NEWLINE = 8;
  /** RegularExpression Id. */
  int PROPTYPE = 9;
  /** RegularExpression Id. */
  int NODEBEGIN = 10;
  /** RegularExpression Id. */
  int NODEEND = 11;
  /** RegularExpression Id. */
  int PROPVALUESEPERATOR = 12;
  /** RegularExpression Id. */
  int COLON = 13;
  /** RegularExpression Id. */
  int LONG = 14;
  /** RegularExpression Id. */
  int DOUBLE = 15;
  /** RegularExpression Id. */
  int BOOLEAN = 16;
  /** RegularExpression Id. */
  int DATE = 17;
  /** RegularExpression Id. */
  int JCRNAME = 18;
  /** RegularExpression Id. */
  int JCRNAMESTRING = 19;
  /** RegularExpression Id. */
  int PROPNAME = 20;
  /** RegularExpression Id. */
  int PROPMULTIPLE = 21;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int insideString = 1;
  /** Lexical state. */
  int afterQuote = 2;
  /** Lexical state. */
  int insideProp = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "<STRING>",
    "<token of kind 4>",
    "<token of kind 5>",
    "\" \"",
    "\"\\t\"",
    "<NEWLINE>",
    "<PROPTYPE>",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\":\"",
    "<LONG>",
    "<DOUBLE>",
    "<BOOLEAN>",
    "<DATE>",
    "<JCRNAME>",
    "<JCRNAMESTRING>",
    "<PROPNAME>",
    "\"*\"",
    "\" \"",
    "\"\\t\"",
  };

}
